---
title: "Introduction to Bayesian hierarchical modelling using R: course timetable"
author: "Andrew Parnell"
date: "July 2019"
output: html_document
---

Module pre-requisites can be found [here](https://andrewcparnell.github.io/bhm_course/Prerequisites.html). All the raw files and code can be found [here](https://www.github.com/andrewcparnell/bhm_course) (click 'Download ZIP' near the top right if you want offline versions of everything). All links below are in pdf format for you to annotate. A glossary of technical terms is [here](https://andrewcparnell.github.io/bhm_course/glossary.html).

## Day 1: Basic concepts

Time  | Class
------------- | ----------------------------------------------------
9:30-10:30 | [Introduction to Bayesian hierarchical models](https://andrewcparnell.github.io/bhm_course/slides/class_1_intro.pdf)
10:30-10:45 | Coffee break
10:45-11:45 | [Likelihood and inference](https://andrewcparnell.github.io/bhm_course/slides/class_2_inference.pdf)
11:45-12:00 | Coffee Break 
12:00-12:45 | Guided practical: Loading data in R and running simple analysis [(R code)](https://andrewcparnell.github.io/bhm_course/practicals/tutor_1_R_basics.R)
12:45-14:00 | Lunch
14:00-17:00 | Self-guided practical (including coffee breaks) [(html)](https://andrewcparnell.github.io/bhm_course/practicals/practical_1_using_R_for_lr_and_glms.html) [(pdf)](https://andrewcparnell.github.io/bhm_course/practicals/practical_1_using_R_for_lr_and_glms.pdf)

## Day 2: Bayesian statistical modelling

Time  | Class
------------- | ----------------------------------------------------
9:30-10:30 | [Introduction to Bayesian statistics](https://andrewcparnell.github.io/bhm_course/slides/class_3_intro_bayes.pdf) 
10:30-10:45 | Coffee break
10:45-11:45 | [Bayesian linear and generalised linear models (GLMs)](https://andrewcparnell.github.io/bhm_course/slides/class_4_bglms.pdf) 
11:45-12:00 | Coffee break
12:00-12:45 | Guided practical: Using R, Jags and Stan for fitting GLMs [(R code)](https://andrewcparnell.github.io/bhm_course/practicals/tutor_2_R_jags_stan.R)
12:45-14:00 | Lunch
14:00-17:00 | Self-guided practical [(html)](https://andrewcparnell.github.io/bhm_course/practicals/practical_2_R_jags_stan_GLMs.html) [(pdf)](https://andrewcparnell.github.io/bhm_course/practicals/practical_2_R_jags_stan_GLMs.pdf)

## Day 3: Hierarchical modelling

Time  | Class
------------- | ----------------------------------------------------
9:30-10:30 | [Simple hierarchical regression models](https://andrewcparnell.github.io/bhm_course/slides/class_5_hlms.pdf) 
10:30-10:45 | Coffee break
10:45-11:45 | [Hierarchical generalised linear models](https://andrewcparnell.github.io/bhm_course/slides/class_6_hglms.pdf) 
11:45-12:00 | Coffee break
12:00-12:45 | Guided practical: Fitting hierarchical models [(R code)](https://andrewcparnell.github.io/bhm_course/practicals/tutor_3_fit_hm.R)
12:45-14:00 | Lunch
14:00-17:00 | Self-guided practical [(html)](https://andrewcparnell.github.io/bhm_course/practicals/practical_3_hglms.html) [(pdf)](https://andrewcparnell.github.io/bhm_course/practicals/practical_3_hglms.pdf)

## Day 4: Advanced hierarchical models

Time  | Class
------------- | ----------------------------------------------------
9:30-10:30 | [Multivariate and multi-layer hierarchical models](https://andrewcparnell.github.io/bhm_course/slides/class_7_multihms.pdf) 
10:30-10:45 | Coffee break
10:45-11:45 | [Partial pooling, zero-inflation, and missing data](https://andrewcparnell.github.io/bhm_course/slides/class_8_pp_zi_multinom.pdf) 
11:45-12:00 | Coffee break
12:00-12:45 | Guided practical: Advanced examples of hierarchical models [(R code)](https://andrewcparnell.github.io/bhm_course/practicals/tutor_4_adv_hms.R)
12:45-14:00 | Lunch
14:00-17:00 | Self-guided practical [(html)](https://andrewcparnell.github.io/bhm_course/practicals/practical_4_advanced_hglms.html) [(pdf)](https://andrewcparnell.github.io/bhm_course/practicals/practical_4_advanced_hglms.pdf)

## Day 5: Hierarchical models as tools

Click [here](https://docs.google.com/spreadsheets/d/12uN3Mh7OYrAOYDOwmhlyQ8ppcct7KBmfLpSbMcl3oX8/edit?usp=sharing) for meeting spreadsheet

Time  | Class
------------- | ----------------------------------------------------
9:30-10:15 | Variable selection and non-parametrics [Stan version](https://andrewcparnell.github.io/bhm_course/slides/class_9_varsel.pdf) [JAGS version](https://andrewcparnell.github.io/bhm_course/slides/class_9_varsel_JAGS.pdf) 
10:15-10:30 | Coffee break
10:30-13:00 | Bring your data session part 1
13:00-14:00 | Lunch
14:00-17:00 | Bring your data session part 2