---
title: "A step by step guide to performing a Bayesian analysis on a data set"
author: "Andrew Parnell"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. __Exploratory data analysis (EDA)__. Plot your data to explore relationships, look for odd/missing values, and make sure you understand what you are analysing. Write down the key questions that you want to answer for this data set. 
2. __Define variables__. Choose which variables are your response(s), which are continuous covariates, which are categorical covariates.
3. __Initial model building__. Pick a very simple model (maybe a regression model/GLM, maybe something else, depending on your data) and draw a DAG. From the DAG identify which variables will appear in your likelihood and which will require priors.
4. __Find prior distributions__. Either from previously published work, or expertise of the data collectors/scientists behind the data set, try and create informative prior distributions for the relevant parameters. If you have no information, try and put a prior distribution that at least matches the likely range of the data set. If this is impsossible put a vague prior on the parameter (e.g. $N(0, 1000)$).
5. __Run a first model__. Fit your first model in JAGS. Check for convergence using Rhat. These should all be <1.1. Plot and print the output and try to interpret the parameter values. Record the DIC/WAIC for this model. 